---
- hosts: drupal_lamp
  become: yes 
  remote_user: ec2-user
  vars_files:
    - vars/docker_container.yml

  tasks:
    - name: Pull Docker image
      docker_image:
        name: "{{ container_image }}"
        source: pull

    - name: Create container 
      docker_container:
        name: "{{ container_name }}{{ item }}"
        image: "{{ container_image }}"
        command: "{{ container_command }}"
        state: present
      with_sequence: count={{ create_containers }}